### ISSUE TITLE
App sometimes times out to a white screen and you have to force close it to recover 

### ISSUE THREAD

**Issue by RheingoldRiver** [hariettem/Artemis#40] opened 2023-06-25 01:49 UTC
**Describe the bug**
As title

**To Reproduce**
1. Browse a bunch, maybe with a weak connection? 
2. About 1 in 50 times this will repro

**Expected behavior**

**Screenshots**
Idk how to upload from mobile. But it's just a white screen. 

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy 9
 - OS: android 10
 - Version  alpha.1

**Additional context**

Sorry writing on mobile is very hard for me

**Comment by win8linux** [comment] 2023-06-25 04:47
Also experienced this bug on a Xiaomi Mi A1 with Android 9 Pie, but haven't been able to replicate it since.

**Comment by RheingoldRiver** [comment] 2023-06-25 04:47
Here's the screenshot:
![image](https://github.com/hariettem/Artemis/assets/18037011/2a278ec8-5458-4b85-a8ad-37d38ba7c349)

**Comment by win8linux** [comment] 2023-06-25 05:21
Just been able to reproduce this bug on an iPhone 7 Plus with iOS 15.7.6:
![image](https://github.com/hariettem/Artemis/assets/11584387/0bfb2148-08a1-4907-be95-77fe6262fb98)

It's even worse since removing a Artemis from the Recents (closing it) does not get rid of the white screen. The app breaks ***completely ***.

**Comment by RheingoldRiver** [comment] 2023-06-25 06:15
Oh yeah I should add, with Android, the white screen only goes away if/when the page successfully loads. Closing & reopening is like a hard refresh for that page, and thus far I have not yet been able to get it to a state where the app is completely bricked like this but I can well see how this could happen with android too. Maybe if someone could test this with internet artificially throttled? (I don't know how to do this)

**Comment by hariettem** [comment] 2023-07-09 22:45
repro? if so reopen this issue

**Closed by hariettem** 2023-07-09 22:45 UTC
Labels: bug, High
