### ISSUE TITLE
Double clicking a post will open 2 instances of the comments

### ISSUE THREAD

**Issue by JadeLyrae** [hariettem/Artemis#203] opened 2023-07-06 12:52 UTC
**Describe the bug**
Sometimes a post will take a moment to open and in that time you can click on the post multiple times. It will then load a copy of the comments for every time you clicked on the post. And to return to the thread, you need to back out the same number of times.

**To Reproduce**
1. Go to any post
2. Click on the post to open it
3. Try to click it multiple times before it opens, (works best on slow internet)
4. Watch the comments slide out multiple times equal to the number of clicks you did. 

**Expected behavior**
The comments should only load once, no matter how many times you click.

**Screenshots**
Issue only seen mid animation, difficult to capture in screenshot

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S10e]
 - OS: [Android 12]
 - Version [app 0.1.5 update: 2307.06.00.28]

**Additional context**

**Comment by evanfoster** [comment] 2023-07-06 16:57
Might be a dupe of #137, which in turn might be a dupe of #6 

(Posting this so that all of the issues get linked together, makes it easier for a dev to determine if it's a dupe or not)

**Comment by hiimmike** [comment] 2023-07-06 17:10
This happens for me as well, on iPhone XS iOS 16.5.1, Artemis 0.1.5, update 2307.06.00.28 .  I noticed those reports were from Android users so I wanted to share.  Thank you.

**Comment by JadeLyrae** [comment] 2023-07-06 17:24
> 

I didn't recognize it by the issue name, but yeah it is identical to #137, not sure about #6 though.

**Comment by hariettem** [comment] 2023-07-09 22:22
how's this one 0.1.7?

**Comment by JadeLyrae** [comment] 2023-07-09 22:48
> how's this one 0.1.7?

Just updated and tried it out. It's still there. I recorded a video of the bug in case it helps.

https://github.com/hariettem/Artemis/assets/138786970/adecddbc-d56f-451d-b040-de320186ebc0

**Comment by hariettem** [comment] 2023-07-09 23:30
will fix!

**Closed** 2023-08-03 23:48 UTC
Labels: Bug, Android, iOS
