### ISSUE TITLE
iOS: Scroll back to original position when tapping menubar again

### ISSUE THREAD

**Issue by geneccx** [hariettem/Artemis#180] opened 2023-07-04 18:59 UTC
In iOS, there is a common gesture of tapping the menu bar to scroll back to the top.

In Apollo, there's the additional support so that if you tapped the menu bar again, it would scroll you back to your original position. This helped a lot with accidental taps.

**Describe the solution you'd like**
Tapping the menu bar returns you back to the position you were at prior to the first time you tapped.

See Reddit thread for video example.

https://www.reddit.com/r/apolloapp/comments/yvyf84/just_a_reminder_that_if_you_accidentally_tap_the/

**Comment by Rand-o** [comment] 2023-08-05 22:05
I accidentally scroll to the top ALL THE TIME. This feature would be a godsend 😊

**Comment by RheingoldRiver** [comment] 2023-08-08 08:04
This is actually a dupe of #80. I'm gonna close this, and raise the priority of that to Med.

**Closed by RheingoldRiver** 2023-08-08 08:04 UTC
Labels: Enhancement
