### ISSUE TITLE
Multiple repeated inputs are getting buffered and acted on multiple times

### ISSUE THREAD

**Issue by evanfoster** [hariettem/Artemis#137] opened 2023-07-03 04:35 UTC
**Describe the bug**
This first occurred for me when a touch input was registered twice. Basically, buttons and clickable things seem like they can be clicked on multiple times and will be opened repeatedly. This is made worse when trying to load new posts, or when there are multiple buffered inputs for the "Posts" button. The repeated loading appears to use a **lot** of CPU time — my phone got quite hot.

**To Reproduce**
1. Open Artemis and go to the Posts tab
2. Scroll down a screen length or two
3. Scroll down again to make more posts load
4. Repeatedly press the Posts button 5-10 times
5. Repeatedly press on one or more posts in the list, continuing even when the post list is no longer displayed

**Expected behavior**
Repeated inputs aren't buffered, and posts don't get opened multiple times (requiring multiple back button presses to get back to the top level).

**Screenshots**
Here's a screen recording reproducing the issue (to make up for my godawful issue summary): https://youtu.be/Jk23mxJb1eA

The video was too large to attach, so I had to post it to YouTube. It may take some time for higher quality versions of the video to be available.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 13
 - Version [e.g. alpha.1]

**Additional context**
This seems a bit contrived, but I'm a terrible smartphone user and have made this happen a couple of times (although it was never as bad as what I posted in the repro video).

**Comment by win8linux** [comment] 2023-07-03 04:49
This may be a duplicate of https://github.com/hariettem/Artemis/issues/6, which was previously closed.

**Comment by hariettem** [comment] 2023-07-09 23:01
does this repo on 0.1.7?

**Comment by evanfoster** [comment] 2023-07-10 02:06
Let me give it a try.

**Comment by evanfoster** [comment] 2023-07-10 02:08
I'm not able to get results that are as severe, but I'm still seeing the problem. I don't have much time rn to test, but I'm guessing I might be able to get results like the video if I tried

**Comment by hariettem** [comment] 2023-07-10 02:49
@evanfoster just pushed an update that should solve that. Try it out!

**Comment by win8linux** [comment] 2023-07-10 11:16
Seemingly fixed as of the 0.1.7/`2307.10.03.42` update.

**Comment by evanfoster** [comment] 2023-07-10 17:28
It appears better, although I did manage to do something that made multiple posts pop up. I'll try and get a repro case since it's slightly different than the initial issue.

**Closed** 2023-08-03 23:44 UTC
Labels: Bug, Android
