### ISSUE TITLE
Home Screen voting swiping issue

### ISSUE THREAD

**Issue by iphilipp** [hariettem/Artemis#291] opened 2023-07-12 04:19 UTC
**Describe the bug**
When swiping to reveal voting actions in the home screen, they do not reveal properly. They show up all at once behind the content of the post rather than as the post slides over. This occurs on both read and unread posts. Voting actions also do not match theme in _Apollo </3_ theme

**To Reproduce**
1. Go to Home Page
2. Swipe Post from right to left

**Expected behavior**
Voting actions should gradually appear as post slides over.

**Screenshots**
https://github.com/hariettem/Artemis/assets/27243223/9496df28-8ec9-4918-9090-50b70d5aa891

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.5.1
 - Version: 0.1.7
   Update: 2307.12.01.18
   (9ca3ce18-fcd4-4a5f-9601-b14639a015f6)
   Channel: preview

**Comment by geneccx** [comment] 2023-07-13 04:58
I think this is a duplicate of #285

**Comment by iphilipp** [comment] 2023-07-13 05:10
Ah yes it is... it just applies to any post in mine.

**Comment by pvmzqahgyd** [comment] 2023-07-13 09:52
Merged with https://github.com/hariettem/Artemis/issues/285

**Closed by pvmzqahgyd** 2023-07-13 09:52 UTC
Labels: bug
