### ISSUE TITLE
Browser doesn't redirect back to the app in the login dialogue 

### ISSUE THREAD

**Issue by driftywinds** [hariettem/Artemis#356] opened 2023-08-06 06:07 UTC
**Describe the bug**
I am logged in the browser to my artemis.camp account but when I launch the process to grant account access to the app, the browser doesn't redirect back to the app.

**To Reproduce**
1. Open Artemis app
2. Start the login dialogue from the "profile" tab
3. Browser doesn't redirect

**Expected behavior**
The browser the should redirect to the app and allow access to your account.

**Screenshots**

https://github.com/hariettem/Artemis/assets/63164617/80cd641d-5d4b-4f1c-a442-9a2bf0124fd0

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Oxygen OS 13
 - Version: 0.2.0

**Additional context**
No additional context.

**Comment by RheingoldRiver** [comment] 2023-08-08 02:11
Believe this is a dupe of #343 and is now fixed 🎉

**Closed by RheingoldRiver** 2023-08-08 02:11 UTC
