### ISSUE TITLE
Voting quickly causes weird behavior

### ISSUE THREAD

**Issue by kruggiero97** [hariettem/Artemis#45] opened 2023-06-26 19:55 UTC
**Describe the bug**
If you upvote then quickly change your vote to downvote, you get some fun phantom inputs.

**To Reproduce**
1. Go to a posts comment view
2. Click on upvote->downvote->boost in quick succession
3. See error

**Expected behavior**
Most recent tap to be the accepted input for your vote.

**Screenshots**
https://github.com/hariettem/Artemis/assets/49291963/3a8e693f-34f6-4ef5-917a-4c7e7bedee1d

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1
 - Version: alpha.2

**Additional context**
In the attached screen recording I only tapped upvote, then downvote, then boost. See results.

**Comment by win8linux** [comment] 2023-06-27 05:43
This is a duplicate of this earlier issue:
https://github.com/hariettem/Artemis/issues/6

**Closed** 2023-06-28 21:22 UTC
Labels: bug
