### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by LazaroFilm** [hariettem/Artemis#332] opened 2023-07-21 13:41 UTC
**Describe the bug**
Crash with notification

**To Reproduce**
Tap update then tap home. At least that's all I did. 

**Expected behavior**
To not crash...

**Screenshots**
![image](https://github.com/hariettem/Artemis/assets/18351100/a6758ea4-444d-45e1-99ec-f381d10d6ea7)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.5.1 (c)
 - Version: 0.1.7
 - Update: 2307.19.23.54
(37f5454d-3c3f-44b8-b5c8-08cf9bebcbbd)}
 - Channel: preview

**Additional context**
I was... in the bathroom... when it happened? I don't know what other additional context is needed...

**Comment by RheingoldRiver** [comment] 2023-08-07 23:25
Has this happened to you again since?

**Comment by RheingoldRiver** [comment] 2023-08-08 02:18
actually this is a dupe of #334, gonna close in favor of that one which has a lot more details

**Closed by RheingoldRiver** 2023-08-08 02:18 UTC
Labels: Bug, iOS
