### ISSUE TITLE
Post obliterated by links

### ISSUE THREAD

**Issue by chris-y** [hariettem/Artemis#256] opened 2023-07-10 21:02 UTC
**Describe the bug**
A post with an image loss of text and some links is overwritten by some links and comments.

**To Reproduce**
1. This particular post shows the issue https://fedia.io/m/retrogaming@lemmy.world/t/89399/shared-on-Artemis

**Expected behavior**
The full post should be readable

**Screenshots**
![Screenshot_20230710-220011.png](https://github.com/hariettem/Artemis/assets/1818803/5e1180a9-4a82-4ed6-9dec-9dcce3cd41c6)

**Smartphone (please complete the following information):**
 - Device: Moto g200
 - OS: Android 11
 - Version: 0.1.7

Update: 2307.09.19.38
(971bc762-c48a-4ef0-9ee6-701445829077)}

Channel: preview

**Comment by Kraiden** [comment] 2023-07-10 22:07
This looks like a duplicate of [this issue](https://github.com/hariettem/Artemis/issues/197)

**Comment by chris-y** [comment] 2023-07-10 22:18
Apologies, didn't see that one. I think it is the same issue, yes.

**Closed** 2023-07-10 22:22 UTC
