### ISSUE TITLE
Failed to talk to instance error

### ISSUE THREAD

**Issue by Prouvaire** [hariettem/Artemis#269] opened 2023-07-11 06:07 UTC
**Describe the bug**
A "Failed to talk to instance. Click to retry" error appears when clicking 'Posts'. 

Clicking on the User and Settings panels still work.

Searching for magazines still works.

Logging off and logging back on does not resolve the issue.

_Killing the Artemis app process and restarting Artemis DOES resolve the issue._

**To Reproduce**
Have seen this error at least twice, but intermittently. 

Have not been able to reproduce it.

**Expected behavior**
For posts to appear.

**Screenshots**
See attached

**Smartphone (please complete the following information):**
 - Device: Huawei Mediapad M5
 - OS: Android 9
 - Artemis version: 0.1.5 Update 2307.07.231.24

**Additional context**
I have installed Artemis on two devices - a relatively modern LG V60 phone (Android 13) and an older Huawei Mediapad M5 tablet (Android 9). Not sure if using the app on two devices is relevant, but include this as a data point.

![Screenshot_20230711-155645](https://github.com/hariettem/Artemis/assets/138431362/b73ff632-a7d2-49b9-9519-8ca6ebf1ee04)

**Comment by RheingoldRiver** [comment] 2023-08-09 09:52
i think this is a dupe of #363, I will keep the more recent one.

**Closed by RheingoldRiver** 2023-08-09 09:52 UTC
Labels: Bug, Android, connection
