### ISSUE TITLE
Add Option to Save Posts/Comments

### ISSUE THREAD

**Issue by NonITExpert** [hariettem/Artemis#185] opened 2023-07-04 21:36 UTC
I don't know in what dev stage this is planned, but wanted to get this submitted now nonetheless. Please add option to save post/comment like Reddit apps. This is different from share where I believe content can be saved on your device. Instead, "Save" keeps the content in your account.

**Comment by NonITExpert** [comment] 2023-07-06 01:46
Adding an example from a Lemmy app that shows the icon for the save (to your profile/account) function.
![Screenshot_20230705_183754_Jerboa](https://github.com/hariettem/Artemis/assets/138516886/5574c53f-7597-4d1a-b11b-500ef82b86b6)

**Comment by NonITExpert** [comment] 2023-07-07 17:56
Same as issue 132.

**Comment by RheingoldRiver** [comment] 2023-08-08 00:05
Closing as dupe of #132

**Closed by RheingoldRiver** 2023-08-08 00:05 UTC
Labels: Enhancement
