### ISSUE TITLE
Swipe for up/downvote breaks when swiping further than necessary

### ISSUE THREAD

**Issue by lvndr-dev** [hariettem/Artemis#30] opened 2023-06-24 08:18 UTC
**Describe the bug**
Swipe for up/downvote breaks when swiping further than necessary. This leads to the title going way to the left. 

**To Reproduce**
1. Swipe to vote on post, but keep holding down. 
2. Drag further to left.
3. See error

**Expected behavior**
Apollo-like. Pull left 1/5th of the way, and release to upvote. Pull left 2/5th, downvote. 
There is no swipe right - But following Apollo, this should save or boost the post. 

**Screenshots**
[Screenshot](https://files.catbox.moe/mbwo19.png)

**Smartphone (please complete the following information):**
iOS 16.5
iPhone Xs Max

**Additional context**

**Comment by win8linux** [comment] 2023-06-24 09:17
This is a duplicate of https://github.com/hariettem/Artemis/issues/26.

**Closed** 2023-06-24 09:35 UTC
Labels: bug
