### ISSUE TITLE
Title in magazines appears cut

### ISSUE THREAD

**Issue by Amarnamoth** [hariettem/Artemis#372] opened 2023-08-09 14:02 UTC
As the screenshot shows, the titles when opening a post in a magazine appear cut

Pixel 6a running Graphene OS
![Screenshot_20230809-155807](https://github.com/hariettem/Artemis/assets/84014982/5869a7d1-89a5-445d-ae5d-255432d9ce20)

**Comment by RheingoldRiver** [comment] 2023-08-09 23:54
pretty sure it's a dupe of #359 so I'm gonna close it. If this is wrong can you reopen? Thanks!

**Closed by RheingoldRiver** 2023-08-09 23:54 UTC
Labels: Bug, mispositioned element
