### ISSUE TITLE
iOS - certain moderated magazines aren’t visible in subscriptions

### ISSUE THREAD

**Issue by brinazarski** [hariettem/Artemis#200] opened 2023-07-06 06:16 UTC
iOS 16.5, iPhone XR

I moderate a lot of magazines. I can see m/BojackHorseman and m/BuyItForLife in my subscription, but not m/castiron. If I go to the magazines, they show that I am subscribed.

**Comment by XiaoKe89** [comment] 2023-07-06 06:22
This is likely the same as issue #142 , easy way to tell is go on the website, go to your settings, then subscriptions, currently the only subscriptions that show in Artemis are from that first page which is the first 48 magazines/communities you subscribed to

**Comment by hariettem** [comment] 2023-07-09 23:29
closing as dupe of #142

**Closed by hariettem** 2023-07-09 23:29 UTC
