### ISSUE TITLE
Allow navigating to "closed" view by swiping from right to left

### ISSUE THREAD

**Issue by geneccx** [hariettem/Artemis#204] opened 2023-07-06 16:30 UTC
**Is your feature request related to a problem? Please describe.**
On many pages, you can swipe from left to right to go back to the previous page.
For example, swiping from left to right on a post brings you to the magazine list, much like the back button on a browser.
Accidentally closing the view leaves no way to go back.

**Describe the solution you'd like**
It would be nice to be able to go the other way, like the forward button on a browser.
More broadly, it would be nice if this was incorporated into navigation throughout the app.

**Additional context**
Sample video of the interaction, from Apollo (rip):
https://github.com/hariettem/Artemis/assets/1152573/cb1c4d82-4c76-4111-8776-970a0cc91ef6

**Comment by RheingoldRiver** [comment] 2023-08-08 07:55
Believe this is a dupe of #77 ?

**Closed** 2023-08-08 07:56 UTC
Labels: Enhancement
