### ISSUE TITLE
Tapping Lower Screen Closes "Sort By" Filter

### ISSUE THREAD

**Issue by F1zzyD** [hariettem/Artemis#154] opened 2023-07-03 19:03 UTC
**Is your feature request related to a problem? Please describe.**
I always like when I open a menu to tap anywhere on the screen and it will just close it. Right now when you open the "Sort By" menu, you have to tap the same icon (fire icon) that you used to open it to close it.

**Describe the solution you'd like**
It would be nice to tap anywhere on the lower half of the screen and the "Sort By" menu would automatically close.

**Comment by Pankakke** [comment] 2023-07-03 22:34
Duplicate of issue #95

**Comment by hariettem** [comment] 2023-07-09 23:06
fixed and dupe :)

**Closed by hariettem** 2023-07-09 23:06 UTC
Labels: enhancement
